import { Router } from 'express';
import { query } from '../config/db';
import { n8nAuth } from '../middleware/auth';
import { createOrder } from './orders';
const router=Router();router.use(n8nAuth);
function restaurantId(req:any){return req.headers['x-restaurant-id'] as string;}
router.get('/restaurant',async(req,res)=>{const r=await query('SELECT id,name,phone,address,description,working_hours AS "workingHours",delivery,payment_methods AS "paymentMethods",knowledge FROM restaurants WHERE id=$1',[restaurantId(req)]);if(!r.rowCount)return res.status(404).json({message:'Restaurant not found'});res.json(r.rows[0]);});
router.get('/menu',async(req,res)=>{const id=restaurantId(req);const [cats,items,images]=await Promise.all([query('SELECT * FROM categories WHERE restaurant_id=$1 AND is_active=true ORDER BY created_at',[id]),query('SELECT mi.*,c.name AS category FROM menu_items mi JOIN categories c ON c.id=mi.category_id WHERE mi.restaurant_id=$1 ORDER BY mi.created_at',[id]),query('SELECT * FROM menu_images WHERE restaurant_id=$1 AND is_active=true ORDER BY display_order',[id])]);res.json({categories:cats.rows,items:items.rows,menuImages:images.rows});});
router.get('/customers/:phone',async(req,res)=>{const r=await query('SELECT * FROM customers WHERE restaurant_id=$1 AND phone=$2',[restaurantId(req),req.params.phone]);if(!r.rowCount)return res.status(404).json({message:'Customer not found'});res.json(r.rows[0]);});
router.post('/customers',async(req,res)=>{const id=restaurantId(req);const r=await query(`INSERT INTO customers(id,restaurant_id,name,phone,address) VALUES($1,$2,$3,$4,$5) ON CONFLICT(restaurant_id,phone) DO UPDATE SET name=EXCLUDED.name,address=COALESCE(EXCLUDED.address,customers.address),updated_at=NOW() RETURNING *`,[require('crypto').randomUUID(),id,req.body.name,req.body.phone,req.body.address||null]);res.status(201).json(r.rows[0]);});
router.post('/orders',async(req,res)=>{try{res.status(201).json(await createOrder(restaurantId(req),req.body));}catch(e:any){res.status(400).json({message:e.message});}});
router.get('/orders/:orderId',async(req,res)=>{const r=await query(`SELECT o.*,c.name AS customer_name,c.phone AS customer_phone,COALESCE(json_agg(json_build_object('productId',oi.product_id,'name',oi.product_name,'quantity',oi.quantity,'price',oi.price,'total',oi.total)) FILTER (WHERE oi.id IS NOT NULL),'[]') AS items FROM orders o JOIN customers c ON c.id=o.customer_id LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.restaurant_id=$1 AND o.order_id=$2 GROUP BY o.id,c.name,c.phone`,[restaurantId(req),req.params.orderId]);if(!r.rowCount)return res.status(404).json({message:'Order not found'});res.json(r.rows[0]);});
router.patch('/orders/:orderId/status',async(req,res)=>{const valid=['Pending','Confirmed','In Kitchen','Out for Delivery','Delivered','Cancelled'];const next=String(req.body.status||'');if(!valid.includes(next))return res.status(400).json({message:'Invalid status'});const r=await query('UPDATE orders SET status=$1,updated_at=NOW() WHERE restaurant_id=$2 AND order_id=$3 RETURNING *',[next,restaurantId(req),req.params.orderId]);if(!r.rowCount)return res.status(404).json({message:'Order not found'});res.json(r.rows[0]);});
router.patch('/orders/:orderId/cancel',async(req,res)=>{const r=await query('SELECT * FROM orders WHERE restaurant_id=$1 AND order_id=$2',[restaurantId(req),req.params.orderId]);if(!r.rowCount)return res.status(404).json({message:'Order not found'});if(['Delivered','Cancelled'].includes(r.rows[0].status))return res.status(400).json({message:'Order cannot be cancelled'});const updated=await query('UPDATE orders SET status=\'Cancelled\',updated_at=NOW() WHERE id=$1 RETURNING *',[r.rows[0].id]);res.json(updated.rows[0]);});
router.get('/menu/images',async(req,res)=>res.json((await query('SELECT * FROM menu_images WHERE restaurant_id=$1 AND is_active=true ORDER BY display_order',[restaurantId(req)])).rows));
export default router;
